name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Pull Docker image
      run: sudo docker pull rishikt/elearn-backend:latest

    - name: Delete Old docker container
      run: sudo docker rm -f elearn-backend || true

    - name: Run Docker Container
      run: sudo docker run -d -p 8080:5000 --name elearn-backend rishikt/elearn-backend:latest
